name: Release

on:
  workflow_run:
    workflows:
      - "Main"
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write # for OIDC
  actions: read # for downloading artifacts

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true
      - run: vp install
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vp-build-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
          version: vp run version
